<!DOCTYPE html>
<html>
<head>
  <title>Uros And Dejan GPT architecture</title>
  <style>
    /* <!DOCTYPE html>
<html>
<head>
  <title>Your Website Title</title>
  <style>
    /* CSS styles go here */
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 10px;
    }

    nav {
      background-color: #f8f8f8;
      padding: 10px;
    }

    main {
      padding: 20px;
    }

    footer {
      background-color: #333;
      color: #fff;
      padding: 10px;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <!-- Header content goes here -->
    <h1>Welcome to My Website</h1>
  </header>

  <nav>
    <!-- Navigation menu goes here -->
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>

  <main>
    <!-- Main content goes here -->
    <h2>About Me</h2>
    <p>I am a web developer passionate about creating beautiful and functional websites.</p>
  </main>

  <footer>
    <!-- Footer content goes here -->
    &copy; 2023 My Website. All rights reserved.
  </footer>
</body>
</html>
 */
  </style>
</head>
<body>
  <header>
    <!-- Header content goes here -->
  </header>

  <nav>
    <!-- Navigation menu goes here -->
  </nav>

  <main>
    <!-- Main content goes here -->
  </main>

  <footer>
    <!-- Footer content goes here -->
  </footer>
</body>
</html>
